import Head from "next/head";
import styles from "../styles/styles.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "./components/BlogCard";
import Categories from "./components/Categories";

const graphcms = new GraphQLClient(
  "https://api-eu-central-1.graphcms.com/v2/cl3wv4w54h7rp01z61synewo1/master"
);

const QUERY = gql`
  {
    posts(orderBy: createdAt_DESC) {
      title
      id
      datePublished
      slug
      content {
        html
      }
      categories {
        id
        name
      }
      author {
        name
        avatar {
          url
        }
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jenni Strand</title>
        <meta
          name="Blog for Jenni Strand"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.posts}>
        <div>
          {posts.map((post) => (
            <BlogCard
              title={post.title}
              key={post.id}
              author={post.author}
              datePublished={post.datePublished}
              slug={post.slug}
              content={post.content}
              categories={post.categories}
            />
          ))}
        </div>
        <div>
          {posts.map((posts) => (
            <Categories categories={posts.categories} key={posts.id} />
          ))}
        </div>
      </main>
    </div>
  );
}
